# Freshdesk Custom App 백엔드 서비스
# 프로젝트 규칙 및 가이드라인: /PROJECT_RULES.md 참조
#version: "3.8"
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: backend
    container_name: project-a
    environment:
      # 로그 레벨 설정 (ERROR로 설정하여 시작시 상세 로그 숨김)
      - LOG_LEVEL=ERROR
      # 표준화된 환경변수 사용
      - TENANT_ID=${TENANT_ID}
      - FRESHDESK_API_KEY=${FRESHDESK_API_KEY}
      - FRESHDESK_DOMAIN=${FRESHDESK_DOMAIN}
      #- DEFAULT_TENANT_ID=${DEFAULT_TENANT_ID}
      # LLM API 키들
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      # Qdrant Cloud 사용 (로컬 Qdrant 서비스 제거됨)
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      # Redis 설정 (필요시)
      - REDIS_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    env_file:
      - ./.env
    depends_on:
      - redis

  redis:
    image: redis:7.2-alpine
    container_name: project-a-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    # Redis 설정 (메모리 정책 등)
    sysctls:
      - net.core.somaxconn=1024

volumes:
  redis_data:
    driver: local
