# Freshdesk Custom App 백엔드 서비스
# 프로젝트 규칙 및 가이드라인: /PROJECT_RULES.md 참조
version: "3.8"
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    image: backend
    container_name: project-a
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FRESHDESK_API_KEY=${FRESHDESK_API_KEY}
      - FRESHDESK_DOMAIN=${FRESHDESK_DOMAIN}
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - REDIS_URL=redis://redis:6379/0
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
    ports:
      - "8000:8000"
    volumes:
      - ./qdrant_data:/app/qdrant_data
      - ./:/app
    env_file:
      - ./.env
    depends_on:
      - qdrant
      - redis

  qdrant:
    image: qdrant/qdrant:latest
    container_name: project-a-qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage
    environment:
      - QDRANT_ALLOW_ORIGIN=*
    restart: unless-stopped

  redis:
    image: redis:7.2-alpine
    container_name: project-a-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    # Redis 설정 (메모리 정책 등)
    sysctls:
      - net.core.somaxconn=1024

volumes:
  redis_data:
    driver: local
