# 보안 민감 정보 템플릿
# 이 파일은 실제 시크릿 값이 아닌 템플릿입니다.
# 실제 환경에서는 AWS Secrets Manager, Azure Key Vault, K8s Secret 등을 사용합니다.

# API 키 템플릿 (실제 값은 보안 저장소에서 관리)
api_keys:
  openai:
    # 개발 환경용 (낮은 한도)
    dev_key: "${OPENAI_DEV_API_KEY}"
    # 프로덕션 환경용 (높은 한도)
    prod_key: "${OPENAI_PROD_API_KEY}"
    # 조직 ID (옵션)
    organization_id: "${OPENAI_ORG_ID}"
    
  anthropic:
    dev_key: "${ANTHROPIC_DEV_API_KEY}"
    prod_key: "${ANTHROPIC_PROD_API_KEY}"
    
  gemini:
    dev_key: "${GEMINI_DEV_API_KEY}"
    prod_key: "${GEMINI_PROD_API_KEY}"
    # 프로젝트 ID
    project_id: "${GOOGLE_CLOUD_PROJECT_ID}"

# 데이터베이스 연결 정보
database:
  qdrant:
    host: "${QDRANT_HOST}"
    port: "${QDRANT_PORT}"
    api_key: "${QDRANT_API_KEY}"
    collection_prefix: "${QDRANT_COLLECTION_PREFIX}"
    
  redis:
    host: "${REDIS_HOST}"
    port: "${REDIS_PORT}"
    password: "${REDIS_PASSWORD}"
    db: "${REDIS_DB}"

# 모니터링 및 로깅
monitoring:
  datadog:
    api_key: "${DATADOG_API_KEY}"
    app_key: "${DATADOG_APP_KEY}"
    
  elasticsearch:
    host: "${ELASTICSEARCH_HOST}"
    username: "${ELASTICSEARCH_USERNAME}"
    password: "${ELASTICSEARCH_PASSWORD}"
    
  prometheus:
    push_gateway: "${PROMETHEUS_PUSH_GATEWAY}"
    auth_token: "${PROMETHEUS_AUTH_TOKEN}"

# 알림 설정
notifications:
  slack:
    webhook_url: "${SLACK_WEBHOOK_URL}"
    error_channel: "${SLACK_ERROR_CHANNEL}"
    
  email:
    smtp_host: "${SMTP_HOST}"
    smtp_user: "${SMTP_USER}"
    smtp_password: "${SMTP_PASSWORD}"
    admin_emails: "${ADMIN_EMAIL_LIST}"

# 외부 서비스 연동
external_services:
  freshdesk:
    api_key: "${FRESHDESK_API_KEY}"
    domain: "${FRESHDESK_DOMAIN}"
    
  github:
    token: "${GITHUB_TOKEN}"
    webhook_secret: "${GITHUB_WEBHOOK_SECRET}"

# 암호화 키
encryption:
  # 설정 암호화용 키
  config_encryption_key: "${CONFIG_ENCRYPTION_KEY}"
  # JWT 서명용 키
  jwt_secret: "${JWT_SECRET_KEY}"
  # 세션 암호화용 키
  session_secret: "${SESSION_SECRET_KEY}"

# 환경별 시크릿 매핑
environment_secrets:
  local:
    # 로컬 개발용 - 개발용 API 키 사용
    openai_api_key: "${api_keys.openai.dev_key}"
    anthropic_api_key: "${api_keys.anthropic.dev_key}"
    gemini_api_key: "${api_keys.gemini.dev_key}"
    
  aws_dev:
    # AWS 개발 환경 - AWS Secrets Manager에서 로드
    openai_api_key: "arn:aws:secretsmanager:us-east-1:123456789:secret:llm/openai/dev-key"
    anthropic_api_key: "arn:aws:secretsmanager:us-east-1:123456789:secret:llm/anthropic/dev-key"
    gemini_api_key: "arn:aws:secretsmanager:us-east-1:123456789:secret:llm/gemini/dev-key"
    
  aws_prod:
    # AWS 프로덕션 환경 - 프로덕션용 시크릿
    openai_api_key: "arn:aws:secretsmanager:us-east-1:123456789:secret:llm/openai/prod-key"
    anthropic_api_key: "arn:aws:secretsmanager:us-east-1:123456789:secret:llm/anthropic/prod-key"
    gemini_api_key: "arn:aws:secretsmanager:us-east-1:123456789:secret:llm/gemini/prod-key"
    
  kubernetes:
    # Kubernetes 환경 - K8s Secret 사용
    openai_api_key: "secret:llm-secrets:openai-api-key"
    anthropic_api_key: "secret:llm-secrets:anthropic-api-key"
    gemini_api_key: "secret:llm-secrets:gemini-api-key"
    
  azure:
    # Azure 환경 - Azure Key Vault 사용
    openai_api_key: "keyvault:llm-keyvault:openai-api-key"
    anthropic_api_key: "keyvault:llm-keyvault:anthropic-api-key"
    gemini_api_key: "keyvault:llm-keyvault:gemini-api-key"

# 시크릿 로테이션 정책
secret_rotation:
  # API 키 로테이션 주기 (일)
  api_keys_rotation_days: 90
  
  # 자동 로테이션 활성화
  auto_rotation_enabled: true
  
  # 로테이션 알림 설정
  rotation_alerts:
    - days_before: 30
      notification: "slack"
    - days_before: 7
      notification: "email"
    - days_before: 1
      notification: "both"

# 접근 제어
access_control:
  # 역할별 시크릿 접근 권한
  roles:
    developer:
      allowed_secrets:
        - "api_keys.*.dev_key"
        - "database.*.dev"
        
    devops:
      allowed_secrets:
        - "api_keys.*.*"
        - "database.*.*"
        - "monitoring.*.*"
        
    admin:
      allowed_secrets:
        - "*"  # 모든 시크릿 접근 가능
        
  # IP 화이트리스트 (옵션)
  ip_whitelist:
    - "10.0.0.0/8"     # 내부 네트워크
    - "172.16.0.0/12"  # 프라이빗 네트워크
    - "192.168.0.0/16" # 로컬 네트워크

# 감사 로깅
audit_logging:
  # 시크릿 접근 로깅
  log_secret_access: true
  
  # 로그 보존 기간 (일)
  log_retention_days: 365
  
  # 로그 저장 위치
  log_destination: "elasticsearch"
  
  # 민감한 값 마스킹
  mask_sensitive_values: true